[package]
name = "git-lock-manager"
version = "1.1.1"
description = "A Git LFS lock GUI"
authors = [ "evopen <520dhh@gmail.com>" ]
license = ""
repository = ""
default-run = "git-lock-manager"
edition = "2018"
build = "src/build.rs"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
tauri = { version = "0.9", features = [ "all-api" ] }
backend-api = { path = "../backend-api" }
nfd2 = "0.2.3"
rayon = "1.5.0"
anyhow = "1.0.33"
fuzzy-matcher = "*"
winapi = "0.3.9"

[target."cfg(windows)".build-dependencies]
winres = "0.1"

[features]
embedded-server = [ "tauri/embedded-server" ]
no-server = [ "tauri/no-server" ]

[[bin]]
name = "git-lock-manager"
path = "src/main.rs"

[profile.release]
lto = true
